DROP TABLE IF EXISTS order_detail;
CREATE TABLE order_detail (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
dish_id BIGINT UNSIGNED NOT NULL,
price FLOAT  NOT NULL,
quantity INT  NOT NULL,
weight FLOAT DEFAULT 1 NOT NULL,
status TINYINT DEFAULT 0 NOT NULL,
order_id INT  NOT NULL,
parent BIGINT UNSIGNED DEFAULT 0 NOT NULL
);

DROP TABLE IF EXISTS table_order;
CREATE TABLE table_order (
id BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
table_id BIGINT UNSIGNED  NOT NULL,
waiter_id BIGINT UNSIGNED NOT NULL,
timestamp TIMESTAMP  NOT NULL,
MD5 CHAR(33) NOT NULL
);

DROP TABLE IF EXISTS dine_info;
CREATE TABLE dine_info (
id BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
table_id BIGINT UNSIGNED  NOT NULL,
advance_payment FLOAT DEFAULT '0' NOT NULL,
persons INT  NOT NULL
);

DROP TABLE IF EXISTS checkout;
CREATE TABLE checkout (
id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
sign CHAR(33)  default '' NOT NULL
);