DROP TABLE IF EXISTS [receipt];
CREATE TABLE [receipt] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[index] INTERGER  NOT NULL,
[json] TEXT  NOT NULL,
[orderId] TEXT NOT NULL,
[isAdd] BOOLEAN NOT NULL,
[useFor] INTERGER NOT NULL,
[pend] BOOLEAN NOT NULL,
[type] INTERGER NOT NULL
);

DROP TABLE IF EXISTS [history];
CREATE TABLE [history] (
	[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
	[type] INTERGER  NOT NULL,
	[table] TEXT  NOT NULL,
	[timestamp]  TIMESTAMP  NOT NULL,
	[receipt] TEXT  NOT NULL,
	[extra] CHAR(5)
);