DROP TABLE IF EXISTS receipt;
CREATE TABLE receipt (
id BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
pirnterIndex INT NOT NULL,
json TEXT NOT NULL,
orderId TEXT NOT NULL,
isAdd TINYINT NOT NULL,
useFor TINYINT NOT NULL,
type TINYINT NOT NULL
);

DROP TABLE IF EXISTS history;
CREATE TABLE history (
	id BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	type TINYINT  NOT NULL,
	tableName TEXT  NOT NULL,
	orderTime  TIMESTAMP  NOT NULL,
	receipt TEXT  NOT NULL,
	extra CHAR(10)
);