DROP TABLE IF EXISTS [receipt];
CREATE TABLE [receipt] (
[id] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[index] INTERGER  NOT NULL,
[json] TEXT  NOT NULL,
[orderId] TEXT NOT NULL,
[isAdd] BOOLEAN NOT NULL,
[useFor] INTERGER NOT NULL
);