DROP TABLE IF EXISTS sales_data;
CREATE TABLE sales_data (
id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
dish_id BIGINT UNSIGNED  NOT NULL,
price FLOAT  NOT NULL,
quantity FLOAT  NOT NULL,
waiter_id BIGINT UNSIGNED NOT NULL,
timestamp TIMESTAMP NOT NULL,
order_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE table_dine_info (
id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
table_id BIGINT UNSIGNED NOT NULL,
order_id BIGINT UNSIGNED NOT NULL,
dine_id BIGINT UNSIGNED NOT NULL,
persons INT NOT NULL,
timestamp TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS table_info;
CREATE TABLE table_info (
id BIGINT UNSIGNED  NOT NULL PRIMARY KEY AUTO_INCREMENT,
table_id BIGINT UNSIGNED  NOT NULL,
persons INT NOT NULL,
timestamp TIMESTAMP NOT NULL
);